version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-104-136.compute-1.amazonaws.com
            database: d26p11uqcuggeg
            schema: public
            user: azsumsnvnrmvko
            password: 93e50e248e851e27f30a9f9f9f9b23c51a617e2becfe0eb2203271ec5fcb8b8a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true